Description: >
  Udacity Cloud DevOps Engineer Nanodegree Program - Project 1. 
  Deploy a High Availability Web App With Cloudformation.

Parameters:

  ParamVPCCIRD:
    Description: IP range (CIDR notation)
    Type: String
    Default: 10.0.0.0/16

  ParamPublicSubnet1CIRD:
    Description: IP range (CIDR notation)
    Type: String
    Default: 10.0.1.0/24

  ParamPublicSubnet2CIRD:
    Description: IP range (CIDR notation)
    Type: String
    Default: 10.0.2.0/24

  ParamPrivateSubnet1CIRD:
    Description: IP range (CIDR notation)
    Type: String
    Default: 10.0.3.0/24

  ParamPrivateSubnet2CIRD:
    Description: IP range (CIDR notation)
    Type: String
    Default: 10.0.4.0/24

Resources:

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref ParamVPCCIRD

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Subnets
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ParamPublicSubnet1CIRD
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ParamPublicSubnet2CIRD
      MapPublicIpOnLaunch: true

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ParamPrivateSubnet1CIRD
      MapPublicIpOnLaunch: false

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ParamPrivateSubnet2CIRD
      MapPublicIpOnLaunch: false

  # EIP NAT
  EIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  EIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NAT1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP1.AllocationId
      SubnetId: !Ref PublicSubnet1

  NAT2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP2.AllocationId
      SubnetId: !Ref PublicSubnet2

  # Public Route
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  AssociatePublicRouteTable1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  AssociatePublicRouteTable2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  PublicInternetRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0
